### 필요한 모듈 세팅

In [65]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.1.0


### 데이타 세팅
부스트코스 softmax강의를 참고하였으며, 해당강의에서 제공한 데이타 샘플을 사용하여 아래예제를 공부 및 기록합니다.

In [108]:
xy = np.loadtxt('data-04-zoo.csv', delimiter = ',', dtype=np.float32)

In [109]:
#데이타 확인, 101행 17열로 되어있는 데이터임
print(xy)
print(xy.shape)

[[1. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 3.]
 ...
 [1. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 6.]
 [0. 1. 1. ... 0. 0. 1.]]
(101, 17)


In [110]:
#x데이터 확인
#x데이터는 원본 데이터에서 마지막 열을 제외한 배열의 집합이다.
#즉 해당데이터는 한행에 16가지 feature로 이루어져있고
#총 101개의 x데이터가 들어있는것이다.
#마지막 17번째 feature는 각 x데이터의 최종 해라고 할 수있는 분류값이 나와있다.
x_data = xy[:,:-1]
print(x_data)
print(x_data.shape)

[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 0. 0.]]
(101, 16)


In [111]:
#마지막 17번째 feature
#0-6까지 7가지로 분류 되는 것을 확인할 수있다.
y_data = xy[:, -1]
print(y_data)
print(y_data.shape)

[0. 0. 3. 0. 0. 0. 0. 3. 3. 0. 0. 1. 3. 6. 6. 6. 1. 0. 3. 0. 1. 1. 0. 1.
 5. 4. 4. 0. 0. 0. 5. 0. 0. 1. 3. 0. 0. 1. 3. 5. 5. 1. 5. 1. 0. 0. 6. 0.
 0. 0. 0. 5. 4. 6. 0. 0. 1. 1. 1. 1. 3. 3. 2. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 6. 3. 0. 0. 2. 6. 1. 1. 2. 6. 3. 1. 0. 6. 3. 1. 5. 4. 2. 2. 3. 0. 0. 1.
 0. 5. 0. 6. 1.]
(101,)


### 분류값 선언 및 배열화
softmax함수 계산을 위한 배열 값을 준비해줘야한다.
y데이터를 기반으로 준비할 것

In [112]:
#분류 가짓수를 선언해 준다 0-6
nb_classes = 7

In [113]:
Y_one_hot = tf.one_hot(y_data.astype(np.int32), nb_classes)
print(Y_one_hot)
print(Y_one_hot.shape)

tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 

### W,b 초기값 설정
softmax 사용을 위해 W값을 배열 ((x값의 행 값,(y값의 열값))으로 설정한다.
b값은 (y값의 열값)으로 맞춰준다.)

In [114]:
W = tf.Variable(tf.random.normal((16, nb_classes)), name='weight')
b = tf.Variable(tf.random.normal((nb_classes,)), name = 'bias')

In [115]:
#값 확인
W[0]

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([-0.1312149,  1.0880232, -0.6171837,  1.2881914, -1.2204108,
        1.3029379, -1.2964671], dtype=float32)>

In [116]:
#값 확인
b[0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.6581287>

In [117]:
#variables 값에 담아주기
variables = [W,b]

In [118]:
#값 확인
variables[0][0]

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([-0.1312149,  1.0880232, -0.6171837,  1.2881914, -1.2204108,
        1.3029379, -1.2964671], dtype=float32)>

In [119]:
#값 확인
variables[1][0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.6581287>

### 함수

In [120]:
#기본 선형회귀 함수
def logit_fn(X):
    return tf.matmul(X,W) + b

In [121]:
#softmax함수
#tf.nn.softmax(tf.matmul(X,W) + b) 가능
def hypothesis(X):
    return tf.nn.softmax(logit_fn(X))

In [122]:
#에러율, 오차율을 구하는 함수
def cost_fn(X, Y):
    logits = logit_fn(X)
    cost_i = tf.keras.losses.categorical_crossentropy(y_true=Y, y_pred=logits, 
                                                      from_logits=True)    
    cost = tf.reduce_mean(cost_i)    
    return cost

In [123]:
#경사하강법
def grad_fn(X,Y):
    with tf.GradientTape() as tape:
        loss = cost_fn(X,Y)
        grads = tape.gradient(loss, variables)
        return grads

In [124]:
#정확도, 예측률구하는 함수
def prediction(X,Y):
    pred = tf.argmax(hypothesis(X),1)
    correct_prediction = tf.equal(pred, tf.argmax(Y,1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    return accuracy


In [125]:
def fit(X,Y, epochs=1000, verbose = 100):
    optimizer = tf.keras.optimizers.SGD(learning_rate=0.1)
    for i in range(epochs):
        grads = grad_fn(X,Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i ==0) | ((i+1)%verbose==0):
            acc= prediction(X,Y).numpy()
            loss = cost_fn(X,Y).numpy()
            print('Steps: {} Loss: {}, Acc: {}'.format(i+1, loss, acc))

In [126]:
fit(x_data, Y_one_hot)

Steps: 1 Loss: 4.020371437072754, Acc: 0.0891089141368866
Steps: 100 Loss: 0.5662930011749268, Acc: 0.8217821717262268
Steps: 200 Loss: 0.3781706988811493, Acc: 0.9009901285171509
Steps: 300 Loss: 0.2842300534248352, Acc: 0.9306930899620056
Steps: 400 Loss: 0.22640354931354523, Acc: 0.9405940771102905
Steps: 500 Loss: 0.18729399144649506, Acc: 0.9504950642585754
Steps: 600 Loss: 0.15929216146469116, Acc: 0.9702970385551453
Steps: 700 Loss: 0.13843293488025665, Acc: 0.9702970385551453
Steps: 800 Loss: 0.12239468097686768, Acc: 1.0
Steps: 900 Loss: 0.10972172021865845, Acc: 1.0
Steps: 1000 Loss: 0.09946618229150772, Acc: 1.0


x_test = np.array([[1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1],
                   [1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1]],dtype=np.float32)
Y_one_hot_test = np.array([[1,0,0,0,0,0,0],
                           [1,0,0,0,0,0,0]],dtype=np.float32)

In [142]:
x_test = np.array([[1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1],dtype=np.float32)
Y_one_hot_test = np.array([[1,0,0,0,0,0,0],
                           []],dtype=np.float32)

SyntaxError: invalid syntax (<ipython-input-142-f84cc8a41e25>, line 2)

In [135]:
W[0]

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([ 1.2568738,  0.7963417, -1.0362203,  0.8214337, -1.3501922,
        1.4137075, -1.4880672], dtype=float32)>

In [136]:
b[0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.5212332>

In [137]:
prediction(x_test, Y_one_hot_test)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [138]:
W[0],b[0]

(<tf.Tensor: shape=(7,), dtype=float32, numpy=
 array([ 1.2568738,  0.7963417, -1.0362203,  0.8214337, -1.3501922,
         1.4137075, -1.4880672], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5212332>)

In [139]:
W[0],b[0]

(<tf.Tensor: shape=(7,), dtype=float32, numpy=
 array([ 1.2568738,  0.7963417, -1.0362203,  0.8214337, -1.3501922,
         1.4137075, -1.4880672], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5212332>)

In [140]:
cost_fn(x_test, Y_one_hot_test)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0006901056>