In [4]:
import tensorflow as tf
import pathlib
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

np.set_printoptions(precision=4)

In [5]:
dataset = tf.data.Dataset.from_tensor_slices([8,3,0,8,2,1])
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [6]:
for elem in dataset:
    print(elem.numpy())

8
3
0
8
2
1


In [9]:
it = iter(dataset)
print(next(it).numpy())

8


In [10]:
print(dataset.reduce(0, lambda state, value: state + value).numpy())


22


In [11]:
dataset1= tf.data.Dataset.from_tensor_slices(tf.random.uniform([4,10]))
dataset1.element_spec

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [12]:
dataset1

<TensorSliceDataset shapes: (10,), types: tf.float32>

In [13]:
for elem in dataset1:
    print(elem.numpy())

[0.3769 0.9168 0.852  0.5177 0.5388 0.7084 0.0691 0.3314 0.0055 0.6107]
[0.8909 0.3044 0.034  0.3236 0.953  0.0316 0.1419 0.8954 0.4615 0.6517]
[0.2764 0.9027 0.8696 0.3135 0.3704 0.6845 0.3819 0.0576 0.338  0.425 ]
[0.7544 0.1475 0.4664 0.6065 0.4896 0.2928 0.7322 0.5144 0.0763 0.9139]


In [31]:
dataset2 = tf.data.Dataset.from_tensor_slices((
tf.random.uniform([10]), tf.random.uniform([10,10], maxval=50,dtype=tf.int32)))

dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(10,), dtype=tf.int32, name=None))

In [32]:
dataset2

<TensorSliceDataset shapes: ((), (10,)), types: (tf.float32, tf.int32)>

In [33]:
for elem in dataset2:
    print(elem)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.4263897>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([14,  4, 21, 27, 29, 42, 38, 48,  7, 20], dtype=int32)>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.48391318>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([37,  5,  8, 26, 49,  6, 36, 43, 32, 49], dtype=int32)>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.06976771>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([42, 29, 42, 12, 31, 17, 17, 10, 10, 14], dtype=int32)>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.6551244>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([32, 23, 12, 45, 35, 35, 23, 21,  9, 47], dtype=int32)>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.47340465>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 8, 10, 34,  7,  9, 44, 30, 25, 48, 18], dtype=int32)>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.10695803>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([42, 26, 36, 37, 27, 38, 12, 35,  7, 27], dtype=int32)>)
(<tf.Tensor: shape

In [34]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))
dataset3.element_spec

(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 (TensorSpec(shape=(), dtype=tf.float32, name=None),
  TensorSpec(shape=(10,), dtype=tf.int32, name=None)))

In [35]:
for elem in dataset3:
    print(elem)

(<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.3769, 0.9168, 0.852 , 0.5177, 0.5388, 0.7084, 0.0691, 0.3314,
       0.0055, 0.6107], dtype=float32)>, (<tf.Tensor: shape=(), dtype=float32, numpy=0.4263897>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([14,  4, 21, 27, 29, 42, 38, 48,  7, 20], dtype=int32)>))
(<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.8909, 0.3044, 0.034 , 0.3236, 0.953 , 0.0316, 0.1419, 0.8954,
       0.4615, 0.6517], dtype=float32)>, (<tf.Tensor: shape=(), dtype=float32, numpy=0.48391318>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([37,  5,  8, 26, 49,  6, 36, 43, 32, 49], dtype=int32)>))
(<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.2764, 0.9027, 0.8696, 0.3135, 0.3704, 0.6845, 0.3819, 0.0576,
       0.338 , 0.425 ], dtype=float32)>, (<tf.Tensor: shape=(), dtype=float32, numpy=0.06976771>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([42, 29, 42, 12, 31, 17, 17, 10, 10, 14], dtype=int32)>))
(<tf.Tensor: shape=(10,), 

In [36]:
dataset4 = tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4]))

dataset4.element_spec

SparseTensorSpec(TensorShape([3, 4]), tf.int32)

In [39]:
for elem in dataset4:
    print(elem)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [40]:
dataset4.element_spec.value_type

tensorflow.python.framework.sparse_tensor.SparseTensor